### ISSUE TITLE
Question: how to resize container

### ISSUE THREAD

**Issue by ebridges** [anteloc/obsidian-grafika-plugin#1]
Hi -- great plugin, hope to make a lot of use of it!

There's an implicit value `graphContainer` that seems to specify the size of the overall container for the graph.  So if I make the graph smaller using the `width` and `height` in the options passed to `init`, the graph is just takes up a small area in the larger container.

How can I control the size of the container?

```js
const chartA = echarts.init (graphContainer, null, {
	renderer: "svg",
	width: "300px",
	height: "300px"
});

function expo(value, index, array) {  
  return value ** 2;
}

let vals = [-2, -1, 0, 1, 2]

const option = {
  title: {
    text: 'f(x) = x^2',
    left: 'center'
  },
  	xAxis: {
		data: vals,
	},
	yAxis: {
		type: "value"
	},
	series: [{
		data: vals.map(expo),
		type: "line",
	}],
};
chartA.setOption(option);
```

Example rendering:

<img width="610" alt="image" src="https://github.com/user-attachments/assets/c63b79a6-0e5c-4329-bf10-6b0be2c8ab89">

**Comment by anteloc** [comment]
Hi @ebridges ,  I'm glad you like the plugin!

Regarding fixing the problem with the container, there is one catch: Obsidian adds a container for the code block, and the plugin adds a sandboxed iframe containing the graphContainer inside. 
What this means is that the one in charge of rendering the container is Obsidian, and not the plugin.
As an (ugly!) workaround, you could try adding this to your code:

```javascript
// Adjust these to your needs
window.frameElement.style.width = "300px"; 
window.frameElement.style.height = "300px";

// Keep the rest as it was
const chartA = echarts.init (graphContainer, null, {
	renderer: "svg",
	width: "300px",
	height: "300px"
});
// etc.
```
However, as you will notice, this will alter only the height of the container, but not the width, that's the standard one for a codeblock in Obsidian.

Hope this helps.

**Comment by ebridges** [comment]
That makes sense, and was what I figured. I’ll give your suggestion a go, thanks!
